name: "Dify Build chatbot servies"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select an environment
        options:
          - staging
          - uat
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: langgenius/dify
          ref: refs/tags/1.0.0
