name: "Dify Build chatbot servies"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select an environment
        options:
          - staging
          - uat
 
